# 자동 생성 클래스에 빈등록되어 메모리에 뜬 객체의 멤버변수값 변경

# properties -> yml (refacter, remane) : 타이핑 중복 설정 가능 (. = :)

# 앞 스페이스 두번 = spring. 



# 서버 설정
server:
  port: 1111
  servlet: 
    context-path: /
    # 프로젝트 이름 언급 안하겠다. 
    
    encoding:
      charset: UTF-8

# 뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/bank/
      suffix: .jsp

# 스타터에 있는 객체가 자동설정에 의해 자동으로 메모리 로딩 -> 데이터 소스 객체의 멤버변수 값 변경 (by 세터메서드)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/my-db-test
    username: sa
    password:


      
      
 # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties[hibernate.format_sql]: true
    
# h2 디비에 최적화된 SQL 생성   
 
# true = 생성한 SQL 콘솔에 출력 

# 컬럼이름과 엔티티 클래스의 변수이름을 똑같이 매핑하는 설정

# update = 테이블 있으면 생성 안함, 변수 추가하면 컬럼 자동 추가 / create = 애플리케이션 실행마다 테이블 있으면 drop하고 새로생성, alter (entity 클래스 기준)

# 새로운 primary key 생성하는 알고리즘 적용 안되도록  

# true = 생성되는 SQL이 한줄 아닌 포맷 유지하여 출력되도록함 